version: '3.8'
services:
  news-aggregator:
    image: news-aggregator:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
      - NYT_API_KEY=${NYT_API_KEY}